name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Setup Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22'

    # Install Node.js dependencies
    - name: Install dependencies
      run: |
        if [ ! -f package-lock.json ]; then
          npm install
        else
          npm ci
        fi

    # Build React app
    - name: Build Frontend
      run: CI= npm run build
        
    # Deploy to hosting via FTP
    - name: Deploy to Web Hosting
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./build/  # React build output
        server-dir: ${{ secrets.SERVER_DIR }}
